site_name: Diatoz - Applied AI - Knowledge Base
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - Home:
    - Applied AI: index.md
    - Foundations:
      - Git: git.md
  - Data Analytics: 
    - CATS: cats.md